# Generated by Django 6.0.1 on 2026-04-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='color',
            field=models.CharField(default='#000000', help_text='Color en formato HEX (ej. #6f42c1)', max_length=7),
        ),
    ]
