# Generated by Django 6.0.1 on 2026-04-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='community',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación'),
        ),
    ]
