# Generated by Django 6.0.1 on 2026-03-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='inventory',
            field=models.JSONField(default=list),
        ),
    ]
