# Generated by Django 6.0.1 on 2026-03-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='actions',
            field=models.JSONField(default=list),
        ),
    ]
