# Generated by Django 6.0.1 on 2026-04-10 02:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gamesystems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.CharField(choices=[('book_skull.png', 'Libro con Calavera'), ('book_spells.png', 'Libro de Hechizos'), ('coffin.png', 'Ataud'), ('cthulhu.png', 'Cthulhu'), ('d20.png', 'D20'), ('d20_blue.png', 'D20 Azul'), ('d20_red.png', 'D20 Rojo'), ('dragon_black.png', 'Dragon Negro'), ('dragon_blue.png', 'Dragon Azul'), ('dragon_green.png', 'Dragon Verde'), ('dragon_red.png', 'Dragon Rojo'), ('investigator.png', 'Investigador'), ('spell_fire.png', 'Hechizo de Fuego'), ('sword_magic.png', 'Espada Magica'), ('sword_pair.png', 'Par de Espadas'), ('sword_shield.png', 'Espada con Escudo'), ('vampire_fangs.png', 'Colmillos de Vampiro'), ('vampire_female.png', 'Vampira'), ('vampire_male.png', 'Vampiro'), ('werewolf.png', 'Hombre Lobo')], default='d20.png', max_length=50, verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Sobre mí')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_email_public', models.BooleanField(default=False, verbose_name='Email Público')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('is_phone_public', models.BooleanField(default=False, verbose_name='Mostrar Teléfono')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Ubicación')),
                ('is_location_public', models.BooleanField(default=False, verbose_name='Mostrar Ubicación')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('is_birth_date_public', models.BooleanField(default=False, verbose_name='Mostrar Cumpleaños')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('NB', 'No Binario'), ('GF', 'Género Fluido'), ('AG', 'Agénero'), ('O', 'Otro'), ('P', 'Prefiero no decir')], max_length=2, verbose_name='Género')),
                ('is_gender_public', models.BooleanField(default=False, verbose_name='Mostrar Género')),
                ('experience_level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('veteran', 'Veterano')], default='beginner', max_length=20, verbose_name='Nivel de Experiencia')),
                ('play_style', models.CharField(choices=[('roleplay', 'Full Roleplay (Interpretación)'), ('combat', 'Full Combat (Wargame)'), ('balanced', 'Balanceado (50/50)')], default='balanced', max_length=20, verbose_name='Estilo de Juego')),
                ('is_last_login_public', models.BooleanField(default=False, verbose_name='Mostrar última conexión')),
                ('blocked_users', models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios Bloqueados')),
                ('favorite_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fans', to='gamesystems.gamesystem', verbose_name='Sistema Favorito')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
