# Generated by Django 6.0.1 on 2026-02-20 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('gamesystems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Campaña')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección del Lugar')),
                ('frequency', models.CharField(choices=[('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual')], default='weekly', max_length=20, verbose_name='Frecuencia')),
                ('modality', models.CharField(choices=[('presential', 'Presencial'), ('virtual', 'Virtual'), ('hybrid', 'Híbrido')], default='virtual', max_length=20, verbose_name='Modalidad')),
                ('experience_level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20, verbose_name='Nivel de Juego')),
                ('play_style', models.CharField(choices=[('roleplay', 'Roleplay'), ('combat', 'Combate'), ('balanced', 'Balanceado')], default='balanced', max_length=20, verbose_name='Estilo de Juego')),
                ('price_type', models.CharField(choices=[('free', 'Gratuito'), ('paid', 'De pago')], default='free', max_length=20, verbose_name='Precio')),
                ('is_private', models.BooleanField(default=False, verbose_name='Mesa Privada')),
                ('play_days', models.CharField(max_length=200, verbose_name='Días de Juego')),
                ('start_time', models.TimeField(verbose_name='Hora Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora Fin')),
                ('max_players', models.PositiveIntegerField(default=8, verbose_name='Jugadores Máximos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('characters', models.ManyToManyField(blank=True, help_text='Personajes que participan en esta mesa', related_name='joined_tables', to='characters.character')),
                ('dm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_tables', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, related_name='joined_tables', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamesystems.gamesystem', verbose_name='Sistema de Juego')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('free', 'Libre'), ('progression', 'Progresión'), ('achievement', 'Logro'), ('item', 'Objeto'), ('death', 'Muerte')], default='free', max_length=20, verbose_name='Tipo de Entrada')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True, verbose_name='Es visible para jugadores')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('target_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.character')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tables.table')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TableInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_invitations', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tables.table')),
            ],
            options={
                'unique_together': {('table', 'receiver')},
            },
        ),
    ]
