# Generated by Django 6.0.1 on 2026-04-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_tablenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablenote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
