# Generated by Django 6.0.1 on 2026-04-17 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('tables', '0003_tablenote_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_tables', to='communities.community'),
        ),
        migrations.AddField(
            model_name='table',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_tables', to='communities.event'),
        ),
        migrations.AddField(
            model_name='table',
            name='invite_only',
            field=models.BooleanField(default=False, verbose_name='Solo invitación'),
        ),
        migrations.AddField(
            model_name='table',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archivada'),
        ),
    ]
