# Generated by Django 6.0.1 on 2026-04-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Sistema')),
                ('slug', models.SlugField(help_text='Identificador único (ej: dnd5e, cthulhu)', unique=True)),
                ('description', models.TextField(blank=True)),
                ('schema_definition', models.JSONField(help_text='Estructura JSON que define stats, skills, etc.', verbose_name='Esquema del Sistema')),
                ('primary_color', models.CharField(default='#3498db', help_text='Código Hexadecimal', max_length=7)),
                ('dm_title', models.CharField(default='Director de Juego', help_text='Titulo del Director de Juego', max_length=20)),
                ('players_title', models.CharField(default='Jugadores', help_text='Titulo para los Jugadores', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
